### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by Alexander-Moroz** [AndreyVMarkelov/jira-prometheus-exporter#26]
Hi,
we try to use your plugin,
but rest endpoint returns ~ 20 first values only.
On valid licences (CORE, SOFTWARE) plugin throws NPE:
`2018-05-04 15:52:10,821 http-nio-51234-exec-183 ERROR Alimirzoev.VA 952x3373185x18 oa59u0 172.17.20.73,172.17.252.119 /plugins/servlet/prometheus/metrics [r.a.a.p.promjiraexporter.service.MetricCollectorImpl] Error collect prometheus metrics
java.lang.NullPointerException
  at ru.andreymarkelov.atlas.plugins.promjiraexporter.service.MetricCollectorImpl.collectInternal(MetricCollectorImpl.java:296)
  at ru.andreymarkelov.atlas.plugins.promjiraexporter.service.MetricCollectorImpl.collect(MetricCollectorImpl.java:395)
  at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:183)
  at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:216)
  at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:137)
  at io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:22)
  at ru.andreymarkelov.atlas.plugins.promjiraexporter.servlet.PrometheusExporter.doGet(PrometheusExporter.java:44)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
  at com.atlassian.plugin.servlet.DelegatingPluginServlet.service(DelegatingPluginServlet.java:37)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
  at com.atlassian.plugin.servlet.ServletModuleContainerServlet.service(ServletModuleContainerServlet.java:45)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
  ... 52 filtered
  at com.atlassian.web.servlet.plugin.request.RedirectInterceptingFilter.doFilter(RedirectInterceptingFilter.java:21)
  ... 58 filtered
  at com.atlassian.jira.security.JiraSecurityFilter.lambda$doFilter$0(JiraSecurityFilter.java:80)
  ... 1 filtered
  at com.atlassian.jira.security.JiraSecurityFilter.doFilter(JiraSecurityFilter.java:78)
  ... 16 filtered
  at ru.andreymarkelov.atlas.plugins.promjiraexporter.servlet.AllEndpointFilter.lambda$doFilter$0(AllEndpointFilter.java:38)
  at ru.andreymarkelov.atlas.plugins.promjiraexporter.service.MetricCollectorImpl.requestDuration(MetricCollectorImpl.java:243)
  at ru.andreymarkelov.atlas.plugins.promjiraexporter.servlet.AllEndpointFilter.doFilter(AllEndpointFilter.java:38)
  ... 24 filtered
  at com.atlassian.jira.servermetrics.CorrelationIdPopulatorFilter.doFilter(CorrelationIdPopulatorFilter.java:30)
  ... 5 filtered
  at com.valiantys.jira.plugins.sql.service.servicedesk.ContextListenerServletFilter.doFilter(ContextListenerServletFilter.java:24)
  ... 8 filtered
  at com.atlassian.web.servlet.plugin.request.RedirectInterceptingFilter.doFilter(RedirectInterceptingFilter.java:21)
  ... 4 filtered
  at com.atlassian.web.servlet.plugin.LocationCleanerFilter.doFilter(LocationCleanerFilter.java:36)
  ... 29 filtered
  at com.atlassian.jira.servermetrics.MetricsCollectorFilter.doFilter(MetricsCollectorFilter.java:25)
  ... 28 filtered
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)`

**Comment by johnwyde** [comment]
+1

**Comment by AndreyVMarkelov** [comment]
Thank you. Will fix ASAP

пт, 4 Май 2018 г., 16:10 Alexander Moroz <notifications@github.com>:

**Comment by AndreyVMarkelov** [comment]
Done
